name: wtg_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  http: ^1.2.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  intl: any
  
  # A dependência 'flutter_svg' foi removida pois não é mais necessária

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Declaração atualizada para os arquivos PNG
  assets:
    - assets/images/LaRuaLogo.png
    - assets/images/LaRuaNameLogo.png
    - assets/images/google_logo.png
    - assets/images/Celebration.png 